CREATE TABLE assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    lesson_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    due_date TIMESTAMPTZ,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_assignment
        PRIMARY KEY (id),

    CONSTRAINT fk_assignment_lesson
        FOREIGN KEY (lesson_id)
        REFERENCES lesson(id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_assignment_status
        CHECK (status IN ('DRAFT', 'PUBLISHED'))
);

CREATE INDEX idx_assignment_lesson
    ON assignment(lesson_id);
