CREATE TABLE submission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    assignment_id BIGINT NOT NULL,
    student_user_account_id BIGINT NOT NULL,
    stored_file_id BIGINT NOT NULL,
    submitted_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(30) NOT NULL,
    grade DECIMAL(4,2),
    feedback TEXT,
    corrected_by_user_account_id BIGINT,
    corrected_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_submission
        PRIMARY KEY (id),

    CONSTRAINT uq_submission_assignment_student
        UNIQUE (assignment_id, student_user_account_id),

    CONSTRAINT fk_submission_assignment
        FOREIGN KEY (assignment_id)
        REFERENCES assignment(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_submission_student
        FOREIGN KEY (student_user_account_id)
        REFERENCES user_account(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_submission_file
        FOREIGN KEY (stored_file_id)
        REFERENCES stored_file(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_submission_corrected_by
        FOREIGN KEY (corrected_by_user_account_id)
        REFERENCES user_account(id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_submission_grade
        CHECK (grade IS NULL OR (grade >= 0 AND grade <= 20)),

    CONSTRAINT ck_submission_status
        CHECK (status IN ('SUBMITTED', 'CORRECTED'))
);

CREATE INDEX idx_submission_assignment ON submission(assignment_id);
CREATE INDEX idx_submission_student ON submission(student_user_account_id);
CREATE INDEX idx_submission_corrected_by ON submission(corrected_by_user_account_id);
