CREATE TABLE training_class (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    course_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_training_class
        PRIMARY KEY (id),

    CONSTRAINT fk_training_class_course
        FOREIGN KEY (course_id)
        REFERENCES course(id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_training_class_course
    ON training_class(course_id);
