CREATE TABLE role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,

    CONSTRAINT pk_role
        PRIMARY KEY (id),

    CONSTRAINT uq_role_code
        UNIQUE (code)
);

INSERT INTO role (code, name)
VALUES
    ('STUDENT', 'Student'),
    ('TRAINER', 'Trainer'),
    ('ADMIN', 'Admin');
