CREATE TABLE user_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    role_id BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_user_account
        PRIMARY KEY (id),

    CONSTRAINT uq_user_account_email
        UNIQUE (email),

    CONSTRAINT fk_user_account_role
        FOREIGN KEY (role_id)
        REFERENCES role(id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_user_account_role
    ON user_account(role_id);

CREATE INDEX idx_user_account_active
    ON user_account(is_active);
