CREATE TABLE course (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(30) NOT NULL,
    category VARCHAR(30) NOT NULL,
    created_by_user_account_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_course
        PRIMARY KEY (id),

    CONSTRAINT fk_course_created_by
        FOREIGN KEY (created_by_user_account_id)
        REFERENCES user_account(id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_course_status
        CHECK (status IN ('DRAFT', 'PUBLISHED')),

    CONSTRAINT ck_course_category
        CHECK (category IN ('LANGUAGES', 'OFFICE_AUTOMATION', 'EDUCTOUR'))
);

CREATE INDEX idx_course_created_by ON course(created_by_user_account_id);
CREATE INDEX idx_course_status ON course(status);
CREATE INDEX idx_course_category ON course(category);
