CREATE TABLE course_module (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    course_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    display_order INTEGER NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_course_module
        PRIMARY KEY (id),

    CONSTRAINT uq_course_module_order
        UNIQUE (course_id, display_order),

    CONSTRAINT fk_course_module_course
        FOREIGN KEY (course_id)
        REFERENCES course(id)
        ON DELETE CASCADE,

    CONSTRAINT ck_course_module_order
        CHECK (display_order > 0),

    CONSTRAINT ck_course_module_status
        CHECK (status IN ('DRAFT', 'PUBLISHED'))
);
