CREATE TABLE lesson (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    course_module_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    content TEXT,
    display_order INTEGER NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_lesson
        PRIMARY KEY (id),

    CONSTRAINT uq_lesson_order
        UNIQUE (course_module_id, display_order),

    CONSTRAINT fk_lesson_course_module
        FOREIGN KEY (course_module_id)
        REFERENCES course_module(id)
        ON DELETE CASCADE,

    CONSTRAINT ck_lesson_order
        CHECK (display_order > 0),

    CONSTRAINT ck_lesson_status
        CHECK (status IN ('DRAFT', 'PUBLISHED'))
);
