CREATE TABLE stored_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    original_name VARCHAR(255) NOT NULL,
    storage_key VARCHAR(500) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    size_bytes BIGINT NOT NULL,
    checksum VARCHAR(255),
    created_by_user_account_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_stored_file
        PRIMARY KEY (id),

    CONSTRAINT uq_stored_file_storage_key
        UNIQUE (storage_key),

    CONSTRAINT fk_stored_file_created_by
        FOREIGN KEY (created_by_user_account_id)
        REFERENCES user_account(id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_stored_file_size
        CHECK (size_bytes > 0 AND size_bytes <= 52428800)
);

CREATE INDEX idx_stored_file_created_by
    ON stored_file(created_by_user_account_id);
