CREATE TABLE resource (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    lesson_id BIGINT NOT NULL,
    stored_file_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    display_order INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_resource
        PRIMARY KEY (id),

    CONSTRAINT fk_resource_lesson
        FOREIGN KEY (lesson_id)
        REFERENCES lesson(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_resource_stored_file
        FOREIGN KEY (stored_file_id)
        REFERENCES stored_file(id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_resource_order
        CHECK (display_order > 0)
);

CREATE INDEX idx_resource_lesson
    ON resource(lesson_id);

CREATE INDEX idx_resource_stored_file
    ON resource(stored_file_id);
