-- =============================================================================
-- HoneyLMS — Demo data (profile "dev" ONLY, never production)
-- =============================================================================
-- Loaded by Flyway from classpath:db/seed, a location enabled only in
-- application-dev.yml. Repeatable migration (R__): it runs after all versioned
-- migrations and runs again whenever this file changes, so EVERY statement is
-- idempotent (ON CONFLICT DO NOTHING / WHERE NOT EXISTS).
--
-- All demo accounts share the password: Honey2026!
-- Emails use the reserved .test domain (RFC 2606). All content is fictional.
-- Resources and submissions are NOT seeded: they need real files on disk;
-- they are created live during the demo.
-- =============================================================================

-- BCrypt hashes are generated by PostgreSQL ($2a$, cost 10, compatible with
-- Spring's BCryptPasswordEncoder): no hash is hard-coded in the repository.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- -----------------------------------------------------------------------------
-- Users: 1 admin, 2 trainers, 2 students
-- -----------------------------------------------------------------------------
INSERT INTO user_account (email, password_hash, first_name, last_name, role_id)
SELECT u.email, crypt('Honey2026!', gen_salt('bf', 10)), u.first_name, u.last_name, r.id
FROM (VALUES
        ('admin@honeylms.test',      'Alice',   'Bernard', 'ADMIN'),
        ('formateur@honeylms.test',  'Paul',    'Durand',  'TRAINER'),
        ('formatrice@honeylms.test', 'Sofia',   'Garcia',  'TRAINER'),
        ('etudiant@honeylms.test',   'Camille', 'Martin',  'STUDENT'),
        ('etudiant2@honeylms.test',  'Lucas',   'Petit',   'STUDENT')
     ) AS u(email, first_name, last_name, role_code)
JOIN role r ON r.code = u.role_code
ON CONFLICT (email) DO NOTHING;

-- -----------------------------------------------------------------------------
-- Courses (created by the admin — only the Admin creates courses)
-- One DRAFT course to show that drafts never reach the catalogue.
-- -----------------------------------------------------------------------------
INSERT INTO course (title, description, status, category, created_by_user_account_id)
SELECT c.title, c.description, c.status, c.category,
       (SELECT id FROM user_account WHERE email = 'admin@honeylms.test')
FROM (VALUES
        ('Anglais professionnel — B1',
         'Communiquer à l''écrit et à l''oral en contexte professionnel.', 'PUBLISHED', 'LANGUAGES'),
        ('Espagnol — Débutant',
         'Les bases pour se présenter et échanger au quotidien.', 'PUBLISHED', 'LANGUAGES'),
        ('Italien — Débutant',
         'Premiers pas en italien, oral et vocabulaire courant.', 'DRAFT', 'LANGUAGES'),
        ('Excel — Les essentiels',
         'Formules, mise en forme et premiers tableaux croisés.', 'PUBLISHED', 'OFFICE_AUTOMATION'),
        ('Word — Documents professionnels',
         'Styles, modèles et mise en page de documents longs.', 'PUBLISHED', 'OFFICE_AUTOMATION'),
        ('Accueil et conseil voyageur',
         'Les fondamentaux de la relation client en agence.', 'PUBLISHED', 'EDUCTOUR'),
        ('Construire une offre de voyage',
         'De la demande client à la proposition.', 'PUBLISHED', 'EDUCTOUR')
     ) AS c(title, description, status, category)
WHERE NOT EXISTS (SELECT 1 FROM course existing WHERE existing.title = c.title);

-- -----------------------------------------------------------------------------
-- Trainer perimeter (CourseTrainer): Paul = English, Excel, Word ;
-- Sofia = Spanish, Italian, both EDUCTOUR courses.
-- -----------------------------------------------------------------------------
INSERT INTO course_trainer (course_id, trainer_user_account_id)
SELECT c.id, u.id
FROM (VALUES
        ('Anglais professionnel — B1',      'formateur@honeylms.test'),
        ('Excel — Les essentiels',          'formateur@honeylms.test'),
        ('Word — Documents professionnels', 'formateur@honeylms.test'),
        ('Espagnol — Débutant',             'formatrice@honeylms.test'),
        ('Italien — Débutant',              'formatrice@honeylms.test'),
        ('Accueil et conseil voyageur',     'formatrice@honeylms.test'),
        ('Construire une offre de voyage',  'formatrice@honeylms.test')
     ) AS a(course_title, trainer_email)
JOIN course c ON c.title = a.course_title
JOIN user_account u ON u.email = a.trainer_email
ON CONFLICT DO NOTHING;

-- -----------------------------------------------------------------------------
-- Modules (one DRAFT module in the English course)
-- -----------------------------------------------------------------------------
INSERT INTO course_module (course_id, title, description, display_order, status)
SELECT c.id, m.title, m.description, m.display_order, m.status
FROM (VALUES
        ('Anglais professionnel — B1', 'Se présenter et présenter son entreprise', 'Vocabulaire et structures de base.', 1, 'PUBLISHED'),
        ('Anglais professionnel — B1', 'Écrire des emails professionnels', 'Formules, ton et relances.', 2, 'PUBLISHED'),
        ('Anglais professionnel — B1', 'Mener une réunion', 'Module en cours de rédaction.', 3, 'DRAFT'),
        ('Espagnol — Débutant', 'Premiers échanges', 'Saluer, se présenter, demander son chemin.', 1, 'PUBLISHED'),
        ('Excel — Les essentiels', 'Prise en main', 'Interface, saisie et mise en forme.', 1, 'PUBLISHED'),
        ('Excel — Les essentiels', 'Formules et fonctions', 'SOMME, MOYENNE, SI et références.', 2, 'PUBLISHED'),
        ('Word — Documents professionnels', 'Styles et mise en page', 'Structurer un document long.', 1, 'PUBLISHED'),
        ('Accueil et conseil voyageur', 'L''accueil en agence', 'Premier contact et écoute active.', 1, 'PUBLISHED'),
        ('Construire une offre de voyage', 'Analyser la demande', 'Questions clés et profil du voyageur.', 1, 'PUBLISHED')
     ) AS m(course_title, title, description, display_order, status)
JOIN course c ON c.title = m.course_title
ON CONFLICT (course_id, display_order) DO NOTHING;

-- -----------------------------------------------------------------------------
-- Lessons (one DRAFT lesson in English module 2)
-- -----------------------------------------------------------------------------
INSERT INTO lesson (course_module_id, title, description, content, display_order, status)
SELECT cm.id, l.title, l.description, l.content, l.display_order, l.status
FROM (VALUES
        ('Anglais professionnel — B1', 1, 'Se présenter', 'Nom, poste, missions.',
         'Dans cette leçon, vous apprenez à vous présenter en contexte professionnel.' || E'\n\n' ||
         'Exemple : « Hello, my name is Camille, I work as a travel advisor at Honey Group. »', 1, 'PUBLISHED'),
        ('Anglais professionnel — B1', 1, 'Présenter son entreprise', 'Activité, chiffres clés, valeurs.',
         'Décrire l''activité d''une entreprise : secteur, clients, implantation.' || E'\n\n' ||
         'Vocabulaire : headquarters, branch, customer base, core business.', 2, 'PUBLISHED'),
        ('Anglais professionnel — B1', 1, 'Parler de son quotidien au travail', 'Tâches et habitudes.',
         'Utiliser le présent simple pour décrire ses tâches régulières.', 3, 'PUBLISHED'),
        ('Anglais professionnel — B1', 2, 'Structure d''un email', 'Objet, salutation, corps, formule finale.',
         'Un email professionnel suit une structure stable : objet clair, salutation, message, formule de politesse.', 1, 'PUBLISHED'),
        ('Anglais professionnel — B1', 2, 'Le ton et les formules de politesse', 'Formel ou semi-formel.',
         'Choisir entre « Dear Mr Smith » et « Hi John » selon la relation avec le destinataire.', 2, 'PUBLISHED'),
        ('Anglais professionnel — B1', 2, 'Rédiger un email de relance', 'Relancer sans brusquer.',
         'Formules utiles : « I am following up on… », « Could you please let me know… ».', 3, 'PUBLISHED'),
        ('Anglais professionnel — B1', 2, 'Répondre à une réclamation', 'Leçon en cours de rédaction.',
         'Contenu à venir.', 4, 'DRAFT'),
        ('Espagnol — Débutant', 1, 'Saluer et se présenter', 'Hola, buenos días…',
         '« Hola, me llamo Lucas. Soy francés. »', 1, 'PUBLISHED'),
        ('Espagnol — Débutant', 1, 'Demander son chemin', 'Directions et lieux.',
         '« ¿Dónde está la estación? » — « Todo recto y a la derecha. »', 2, 'PUBLISHED'),
        ('Excel — Les essentiels', 1, 'Découvrir l''interface', 'Ruban, cellules, feuilles.',
         'Repérer le ruban, la barre de formule et les onglets de feuilles.', 1, 'PUBLISHED'),
        ('Excel — Les essentiels', 1, 'Saisir et mettre en forme', 'Formats de nombres et bordures.',
         'Appliquer un format monétaire et des bordures à un tableau simple.', 2, 'PUBLISHED'),
        ('Excel — Les essentiels', 2, 'SOMME et MOYENNE', 'Premières fonctions.',
         '=SOMME(B2:B10) additionne une plage ; =MOYENNE(B2:B10) en calcule la moyenne.', 1, 'PUBLISHED'),
        ('Excel — Les essentiels', 2, 'La fonction SI', 'Tester une condition.',
         '=SI(C2>=10;"Validé";"À revoir") affiche un résultat selon une condition.', 2, 'PUBLISHED'),
        ('Word — Documents professionnels', 1, 'Utiliser les styles', 'Titres et paragraphes.',
         'Les styles Titre 1, Titre 2 structurent le document et alimentent la table des matières.', 1, 'PUBLISHED'),
        ('Accueil et conseil voyageur', 1, 'Le premier contact', 'Sourire, posture, reformulation.',
         'Accueillir le client dans les 30 premières secondes et reformuler sa demande.', 1, 'PUBLISHED'),
        ('Accueil et conseil voyageur', 1, 'L''écoute active', 'Questions ouvertes.',
         'Poser des questions ouvertes pour cerner les attentes du voyageur.', 2, 'PUBLISHED'),
        ('Construire une offre de voyage', 1, 'Le profil du voyageur', 'Budget, dates, envies.',
         'Identifier budget, période, durée et centres d''intérêt avant toute proposition.', 1, 'PUBLISHED')
     ) AS l(course_title, module_order, title, description, content, display_order, status)
JOIN course c ON c.title = l.course_title
JOIN course_module cm ON cm.course_id = c.id AND cm.display_order = l.module_order
ON CONFLICT (course_module_id, display_order) DO NOTHING;

-- -----------------------------------------------------------------------------
-- Assignments: one open (deadline in 14 days), one already closed (yesterday)
-- to demonstrate the deadline rule.
-- -----------------------------------------------------------------------------
INSERT INTO assignment (lesson_id, title, description, due_date, status)
SELECT ls.id, a.title, a.description, a.due_date, 'PUBLISHED'
FROM (VALUES
        ('Anglais professionnel — B1', 2, 3, 'Rédiger un email de relance client',
         'Rédigez un email de relance (150 mots environ) à un client qui n''a pas répondu à un devis. Déposez un fichier PDF ou DOCX.',
         CURRENT_TIMESTAMP + INTERVAL '14 days'),
        ('Excel — Les essentiels', 2, 2, 'Tableau de suivi des ventes',
         'Construisez un tableau de suivi des ventes utilisant SOMME, MOYENNE et SI. Déposez le fichier XLSX.',
         CURRENT_TIMESTAMP - INTERVAL '1 day')
     ) AS a(course_title, module_order, lesson_order, title, description, due_date)
JOIN course c ON c.title = a.course_title
JOIN course_module cm ON cm.course_id = c.id AND cm.display_order = a.module_order
JOIN lesson ls ON ls.course_module_id = cm.id AND ls.display_order = a.lesson_order
WHERE NOT EXISTS (SELECT 1 FROM assignment existing WHERE existing.lesson_id = ls.id AND existing.title = a.title);

-- -----------------------------------------------------------------------------
-- Enrollments: Camille follows 3 courses ; Lucas follows none (to demo enrollment)
-- -----------------------------------------------------------------------------
INSERT INTO enrollment (student_user_account_id, course_id, enrolled_at)
SELECT u.id, c.id, CURRENT_TIMESTAMP - e.days_ago * INTERVAL '1 day'
FROM (VALUES
        ('Anglais professionnel — B1', 20),
        ('Excel — Les essentiels', 10),
        ('Accueil et conseil voyageur', 30)
     ) AS e(course_title, days_ago)
JOIN course c ON c.title = e.course_title
JOIN user_account u ON u.email = 'etudiant@honeylms.test'
ON CONFLICT DO NOTHING;

-- -----------------------------------------------------------------------------
-- Progress for Camille:
--   English: module 1 done, module 2 lesson 1 done, lesson 2 viewed last (resume point)
--   Excel: first lesson done
--   Accueil voyageur: everything done (100 %)
-- -----------------------------------------------------------------------------
INSERT INTO lesson_completion (student_user_account_id, lesson_id, completed_at, last_viewed_at)
SELECT u.id, ls.id,
       CASE WHEN p.completed THEN CURRENT_TIMESTAMP - p.hours_ago * INTERVAL '1 hour' END,
       CURRENT_TIMESTAMP - p.hours_ago * INTERVAL '1 hour'
FROM (VALUES
        ('Anglais professionnel — B1', 1, 1, TRUE, 300),
        ('Anglais professionnel — B1', 1, 2, TRUE, 250),
        ('Anglais professionnel — B1', 1, 3, TRUE, 200),
        ('Anglais professionnel — B1', 2, 1, TRUE, 50),
        ('Anglais professionnel — B1', 2, 2, FALSE, 2),
        ('Excel — Les essentiels', 1, 1, TRUE, 100),
        ('Accueil et conseil voyageur', 1, 1, TRUE, 600),
        ('Accueil et conseil voyageur', 1, 2, TRUE, 590)
     ) AS p(course_title, module_order, lesson_order, completed, hours_ago)
JOIN course c ON c.title = p.course_title
JOIN course_module cm ON cm.course_id = c.id AND cm.display_order = p.module_order
JOIN lesson ls ON ls.course_module_id = cm.id AND ls.display_order = p.lesson_order
JOIN user_account u ON u.email = 'etudiant@honeylms.test'
ON CONFLICT DO NOTHING;

-- -----------------------------------------------------------------------------
-- One class (organisation only — never grants access to a course)
-- -----------------------------------------------------------------------------
INSERT INTO training_class (course_id, name, description)
SELECT c.id, 'Promo Octobre 2026 — Anglais', 'Groupe du mardi soir.'
FROM course c
WHERE c.title = 'Anglais professionnel — B1'
  AND NOT EXISTS (SELECT 1 FROM training_class t WHERE t.name = 'Promo Octobre 2026 — Anglais');

INSERT INTO class_student (student_user_account_id, class_id)
SELECT u.id, t.id
FROM training_class t
JOIN user_account u ON u.email = 'etudiant@honeylms.test'
WHERE t.name = 'Promo Octobre 2026 — Anglais'
ON CONFLICT DO NOTHING;

INSERT INTO class_trainer (trainer_user_account_id, class_id)
SELECT u.id, t.id
FROM training_class t
JOIN user_account u ON u.email = 'formateur@honeylms.test'
WHERE t.name = 'Promo Octobre 2026 — Anglais'
ON CONFLICT DO NOTHING;
